version: '3.9'
services:
  db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: ingrid
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: jwt
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - ingrid-network
  rest-with-spring-boot-erudio:
    image: ingrid/jwt-spring-security
    restart: always
    build: ./jwt-spring-security
    working_dir: /jwt-spring-security
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/jwt?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: ingrid
      SPRING.DATASOURCE.PASSWORD: 123
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      ingrid-network:
networks:
  ingrid-network:
    driver: bridge